SET search_path TO onetax, public;

INSERT INTO GI1 (
  field_code,
  field_length,
  data_type,
  decimal_places,
  signed,
  category_1,
  category_2
) VALUES
  ('CS', 12, 'X', 0, 'N', 'NAME', 'WORKER'),
  ('CU', 14, 'X', 0, 'N', 'NAME', 'WORKER'),
  ('DD', 0, 'X', 0, 'N', 'SSN', 'WORKER'),
  ('SY', 8, 'X', 0, 'N', 'DATE', 'WORKER'),
  ('NZ', 8, 'X', 0, 'N', 'DATE', 'WORKER'),
  ('PF', 8, 'X', 0, 'N', 'DATE', 'WORKER'),
  ('EG', 1, 'X', 0, 'N', 'FLAG', 'WORKER'),
  ('DZ', 1, 'X', 0, 'N', 'FLAG', 'WORKER'),
  ('B2', 1, 'X', 0, 'N', 'FLAG', 'WORKER'),
  ('8R', 1, 'X', 0, 'N', 'FLAG', 'WORKER'),
  ('G6', 1, 'X', 0, 'N', 'FLAG', 'FEDERAL'),
  ('G5', 1, 'X', 0, 'N', 'FLAG', 'FEDERAL'),
  ('ED', 1, 'X', 0, 'N', 'FLAG', 'STATE'),
  ('G4', 6, 'X', 0, 'N', 'DEPARTMENT', 'FEDERAL'),
  ('32', 1, 'X', 0, 'N', 'FLAG', 'WORKER'),
  ('CT', 1, 'X', 0, 'N', 'NAME', 'WORKER'),
  ('EF', 1, 'X', 0, 'N', 'FLAG', 'STATE'),
  ('85', 1, 'X', 0, 'N', 'FLAG', 'LOCAL'),
  ('EC', 1, 'X', 0, 'N', 'FLAG', 'STATE'),
  ('9F', 1, 'X', 0, 'N', 'FLAG', 'LOCAL'),
  ('Q9', 1, 'X', 0, 'N', 'FLAG', 'FEDERAL'),
  ('V9', 10, 'X', 0, 'N', 'EMPLOYEE_ID', 'FEDERAL'),
  ('Z3', 80, 'X', 0, 'N', 'JOB', 'STATE'),
  ('A8', 1, 'X', 0, 'N', 'PAY', 'WORKER'),
  ('QG', 1, 'X', 0, 'N', 'FLAG', 'STATE'),
  ('EE', 1, 'X', 0, 'N', 'FLAG', 'WORKER'),
  ('A7', 10, 'N', 4, 'N', 'PAY', 'STATE'),
  ('JZ', 9, 'X', 0, 'N', 'ADDRESS', 'STATE'),
  ('SQ', 30, 'X', 0, 'N', 'ADDRESS', 'WORKER'),
  ('Z5', 40, 'X', 0, 'N', 'ADDRESS', 'WORKER'),
  ('CY', 18, 'X', 0, 'N', 'ADDRESS', 'WORKER'),
  ('Z7', 30, 'X', 0, 'N', 'ADDRESS', 'WORKER'),
  ('DA', 2, 'X', 0, 'N', 'ADDRESS', 'WORKER'),
  ('Z8', 2, 'X', 0, 'N', 'ADDRESS', 'WORKER'),
  ('DB', 9, 'X', 0, 'N', 'ADDRESS', 'WORKER'),
  ('Z9', 9, 'X', 0, 'N', 'ADDRESS', 'WORKER'),
  ('EJ', 12, 'N', 2, 'Y', 'TAX', 'FEDERAL'),
  ('EK', 14, 'N', 2, 'Y', 'TAX', 'FEDERAL'),
  ('MV', 12, 'N', 2, 'Y', 'TAX', 'STATE'),
  ('NT', 12, 'N', 2, 'Y', 'TAX', 'STATE'),
  ('DF', 1, 'X', 0, 'N', 'PROFILE', 'FEDERAL'),
  ('DG', 2, 'N', 0, 'N', 'PROFILE', 'FEDERAL'),
  ('DH', 1, 'X', 0, 'N', 'PROFILE', 'STATE'),
  ('DI', 2, 'N', 0, 'N', 'PROFILE', 'STATE'),
  ('DK', 1, 'X', 0, 'N', 'PROFILE', 'LOCAL'),
  ('DL', 2, 'N', 0, 'N', 'PROFILE', 'LOCAL'),
  ('EA', 1, 'X', 0, 'N', 'PROFILE', 'STATE'),
  ('EB', 1, 'X', 0, 'N', 'PROFILE', 'STATE'),
  ('X1', 6, 'N', 0, 'N', 'PSD', 'LOCAL'),
  ('7H', 12, 'N', 2, 'Y', 'TAX', 'FEDERAL'),
  ('5E', 14, 'N', 2, 'Y', 'TAX', 'FEDERAL')
ON CONFLICT (field_code) DO NOTHING;

INSERT INTO GI2 (
  file_code,
  field_code,
  record_code
) VALUES
  ('Q', 'G6', 'EEF'),
  ('Q', 'G5', 'EEF'),
  ('Q', 'G4', 'EEF'),
  ('Q', 'Q9', 'EEF'),
  ('Q', 'V9', 'EEF'),
  ('Q', 'DF', 'EEF'),
  ('Q', 'DG', 'EEF'),
  ('Q', 'EJ', 'EEF'),
  ('Q', 'EK', 'EEF'),
  ('Q', '7H', 'EEF'),
  ('Q', '5E', 'EEF'),
  ('Q', 'ED', 'EES'),
  ('Q', 'EF', 'EES'),
  ('Q', 'EC', 'EES'),
  ('Q', 'Z3', 'EES'),
  ('Q', 'QG', 'EES'),
  ('Q', 'A7', 'EES'),
  ('Q', 'JZ', 'EES'),
  ('Q', 'DH', 'EES'),
  ('Q', 'DI', 'EES'),
  ('Q', 'EA', 'EES'),
  ('Q', 'EB', 'EES'),
  ('Q', 'MV', 'EES'),
  ('Q', 'NT', 'EES'),
  ('Q', '85', 'EEL'),
  ('Q', '9F', 'EEL'),
  ('Q', 'DK', 'EEL'),
  ('Q', 'DL', 'EEL'),
  ('Q', 'X1', 'EEL')
ON CONFLICT DO NOTHING;

